import Image from 'next/image'
import Head from 'next/head'
import React from 'react';
import { Inter } from 'next/font/google'
import Header from '../components/Header';
import CreateForm from "@/components/createform";
import { useState } from "react";
import Footer from "@/components/footer";
import ReportTable from "@/components/reportTable";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const [tableCount, setTableCount] = useState(0);

  const incrementTableCount = () => {
    setTableCount(tableCount + 1);
  };

  const [reports, setReports] = React.useState([]);

  return (
    <div>
        <Head>
           <title>Cookie Stand Admin</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main>
            <div className="p-8">
                <CreateForm incrementTableCount={incrementTableCount} reports={reports} setReports={setReports}/>


            </div>
            <div className="flex justify-center pt-8 pb-12">
                 {reports.length > 0 ? <ReportTable reports={reports}/> : <h2>No Cookie Stands Available</h2>}
            </div>
        </main>
        <Footer tableCount={tableCount} />
    </div>
  )
}
