import Image from 'next/image'
import Head from 'next/head'
import React from 'react';
import { Inter } from 'next/font/google'
import Header from '../components/Header';
import CreateForm from "@/components/createform";
import { useState } from "react";
import Footer from "@/components/footer";
import ReportTable from "@/components/reportTable";
import { useAuth} from "@/contexts/auth";

import LoginForm from "@/components/loginForm";
import useResource from "@/hooks/useResource";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const { user, login } = useAuth();

    const handleLogin = async (username, password) => {
        try {
            await login(username, password);
        } catch (error) {
            console.log(error);
            console.log(username)
            console.log(password)
        }
    };

    return (
        <div className="p-4">
            <Head>
                <title>Cookie Stand Admin</title>
            </Head>

            {user ?
                <CookieStandAdmin />
                :
                <LoginForm onLogin={handleLogin} />
            }

        </div>
    );
}

function CookieStandAdmin() {


    const [tableCount, setTableCount] = useState(0);

  const incrementTableCount = () => {
    setTableCount(tableCount + 1);
  };

  const { resources, deleteResource } = useResource()
    console.log(resources)



  return (
    <div>
        <Head>
           <title>Cookie Stand Admin</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />

        <main>
            <div className="p-8">
                <CreateForm />


            </div>
            <div className="flex justify-center pt-8 pb-12">
                 {resources ? <ReportTable reports={resources || []} deleteReports={deleteResource}/> : <h2>No Cookie Stands Available</h2>}
            </div>
        </main>
        <Footer tableCount={tableCount} />
    </div>
  )
}
